# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

parameters:
  - name: platforms
    type: object
    default:
    - name: windows
      vmImage: windows-2019
    - name: linux
      vmImage: ubuntu-latest
    - name: mac
      vmImage: macOS-latest

jobs:
- ${{ each platform in parameters.platforms }}:
  - job: ${{ platform.name }}

    pool:
      vmImage: ${{ platform.vmImage }}

    steps:
    - script: bazel --version
      displayName: 'Bazel Version'

    - script: |
        bazel build //tests/sanity
      displayName: 'Sanity Test'
    
    - script: |
        bazel test //tests/HelloBazel:HelloBazel_test
      displayName: 'Hello Bazel from rules_dotnet'

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/test.xml'
        searchFolder: '$(System.DefaultWorkingDirectory)/bazel-testlogs'
        failTaskOnFailedTests: true
        buildPlatform: '${{ platform.name }}'
        testRunTitle: 'bazel test'
      condition: always()