# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

parameters:
- name: platforms
  type: object
  default:
  - name: windows
    vmImage: windows-2019
  - name: linux
    vmImage: ubuntu-latest
  - name: mac
    vmImage: macOS-latest

jobs:
- ${{ each platform in parameters.platforms }}:
  - job: ${{ platform.name }}

    pool:
      vmImage: ${{ platform.vmImage }}

    steps:
    - script: |
        bazel --version
        env | sort
      displayName: 'Environment Info'

    -script: |
        cat > .bazelrc <<EOF
        build --bes_results_url=https://app.buildbuddy.io/invocation/
        build --bes_backend=grpcs://cloud.buildbuddy.io
        build --remote_cache=grpcs://cloud.buildbuddy.io
        build --noremote_upload_local_results # Uploads logs & artifacts without writing to cache
        build --remote_timeout=3600
        build --remote_header=x-buildbuddy-api-key=$(BUILDBUDDY_API_KEY)
        EOF
    - script: |
        bazel build //tests/sanity
      displayName: 'Sanity Test'

    - script: |
        bazel test --test_output=all --sandbox_debug -- //tests/launcher:all
      displayName: 'Dotnet Rules Tests'

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/test.xml'
        searchFolder: '$(System.DefaultWorkingDirectory)/bazel-testlogs'
        failTaskOnFailedTests: true
        buildPlatform: '${{ platform.name }}'
        testRunTitle: '${{ platform.name }}'
        publishRunAttachments: true
      condition: always()