# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

parameters:
  - name: platforms
    type: object
    default:
    - name: windows
      vmImage: windows-2019
    - name: linux
      vmImage: ubuntu-latest
    - name: mac
      vmImage: macOS-latest

jobs:
- ${{ each platform in parameters.platforms }}:
  - job: ${{ platform.name }}

    pool:
      vmImage: ${{ platform.vmImage }}

    steps:
    - script: bazel --version
      displayName: 'Bazel Version'

    - script: |
        env
        which dotnet
      displayName: 'Environment'
    
    - script: |
        bazel build //tests/sanity
      displayName: 'Sanity Test'
    
    - script: |
        bazel test --test_output=all //tests/HelloBazel:HelloBazel_test
      displayName: 'Hello Bazel from rules_dotnet'
      continueOnError: true

    - task: ExtractFiles@1
      displayName: 'Extract test details'
      inputs:
        archiveFilePatterns: 'bazel-testlogs/**/*.zip'
        destinationFolder: 'bazel-testlogs/'
        cleanDestinationFolder: false
        overwriteExistingFiles: true

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/*test.xml'
        searchFolder: '$(System.DefaultWorkingDirectory)/bazel-testlogs'
        failTaskOnFailedTests: true
        buildPlatform: '${{ platform.name }}'
        testRunTitle: '${{ platform.name }}'
        publishRunAttachments: true