# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

parameters:
  - name: platforms
    type: object
    default:
      - name: windows
        vmImage: windows-2019
      - name: linux
        vmImage: ubuntu-latest
      - name: mac
        vmImage: macOS-latest

jobs:
  - ${{ each platform in parameters.platforms }}:
      - job: ${{ platform.name }}
        pool:
          vmImage: ${{ platform.vmImage }}

        steps:
          - bash: .ci/init.sh
            displayName: 'CI Init'
            env:
              BUILDBUDDY_API_KEY: $(BUILDBUDDY_API_KEY)

          - script: |
              bash tests/runall.sh
            displayName: 'Build & Test'

          - script: |
              bash .ci/tar.sh
            displayName: 'tar outputs'
            condition: always()

          - publish: bazel-out.tar.gz
            artifact: bazel-out
            condition: always()

          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '**/test.xml'
              searchFolder: '$(System.DefaultWorkingDirectory)/bazel-testlogs'
              failTaskOnFailedTests: true
              buildPlatform: '${{ platform.name }}'
              testRunTitle: '${{ platform.name }}'
              publishRunAttachments: true
            condition: always()
