trigger:
  - master

jobs:

  - job: working

    pool:
      vmImage: ubuntu-latest

    steps:
      - bash: .ci/init.sh
        displayName: 'Init CI'
        env:
          BUILDBUDDY_API_KEY: $(BUILDBUDDY_API_KEY)

      - script: |
          bazel test //tests/sanity:all
        displayName: 'Sanity Test'

      - script: |
          bazel build //tests/launcher:single
        displayName: 'build greeter'

      - script: |
          bazel build //tests/launcher:double
        displayName: 'test output'

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '**/test.xml'
          searchFolder: '$(System.DefaultWorkingDirectory)/bazel-testlogs'
          failTaskOnFailedTests: true
          publishRunAttachments: true
        condition: always()

  - job: not_working

    pool:
      vmImage: ubuntu-latest

    steps:
      - bash: .ci/init.sh
        displayName: 'Init CI'
        env:
          BUILDBUDDY_API_KEY: $(BUILDBUDDY_API_KEY)

      - script: |
          bazel test //tests/sanity:all
        displayName: 'Sanity Test'

      - script: |
          bazel build //tests/launcher:double
        displayName: 'build & test output'

      - script: tar -zcvf logs.tar.gz bazel-bin/**/*.binlog
        condition: always()

      - publish: $(Build.SourcesDirectory)/logs.tar.gz
        artifact: Binlogs
        condition: always()

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '**/test.xml'
          searchFolder: '$(System.DefaultWorkingDirectory)/bazel-testlogs'
          failTaskOnFailedTests: true
          publishRunAttachments: true
        condition: always()
