name: Sandbox Issue Repro

on:
  push:
    branches: [ sandbox-repro ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # secrets
  BUILDBUDDY_API_KEY:

jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Environment
        run: |
          bazel --version
          env | sort

      - name: RC Setup
        run: ./.ci/make_rc.sh

      - name: Sanity Test
        run: |
          bazel build //tests/sanity:all

      - name: Bazel build
        run: |
          bazel test //tests/launcher:all
