name: Sandbox Issue Repro

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}

jobs:
  working:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: RC Setup
        run: .ci/init.sh

      - name: Sanity Test
        run: |
          bazel test //tests/sanity:all

      - name: Bazel build
        run: |
          bazel build //tests/launcher:run_greeter

      - name: Bazel test
        run: |
          bazel test //tests/launcher:launcher_test

  not_working:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: RC Setup
        run: .ci/init.sh

      - name: Sanity Test
        run: |
          bazel test //tests/sanity:all

      - name: Bazel build & test
        run: |
          bazel test //tests/launcher:launcher_test
