name: Slack reporter

on:
  workflow_run:
    workflows: ["CI"]
    types: 
      - completed
      - requested


jobs:
  report: 
    runs-on: ubuntu-latest
    steps:
    - uses: 8398a7/action-slack@v3
      with:
        status: ${{ github.event.action }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      if: always() # Pick up events even if the job fails or is canceled.
